# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schedule.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schedule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eschedule.proto\"\x14\n\x04\x44\x61te\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"&\n\x08MoviesID\x12\x1a\n\x08moviesid\x18\x01 \x03(\x0b\x32\x08.MovieID\"\x15\n\x07MovieID\x12\n\n\x02id\x18\x01 \x01(\t\"\x1d\n\x05\x44\x61tes\x12\x14\n\x05\x64\x61tes\x18\x01 \x03(\x0b\x32\x05.Date\",\n\x0cScheduleData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"\x07\n\x05\x45mpty2\xba\x01\n\x08Schedule\x12%\n\x0fGetMoviesByDate\x12\x05.Date\x1a\t.MoviesID\"\x00\x12&\n\x10GetDatesForMovie\x12\x08.MovieID\x1a\x06.Dates\"\x00\x12-\n\x0b\x41\x64\x64Schedule\x12\r.ScheduleData\x1a\r.ScheduleData\"\x00\x12\x30\n\x0e\x44\x65leteSchedule\x12\r.ScheduleData\x1a\r.ScheduleData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schedule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATE']._serialized_start=18
  _globals['_DATE']._serialized_end=38
  _globals['_MOVIESID']._serialized_start=40
  _globals['_MOVIESID']._serialized_end=78
  _globals['_MOVIEID']._serialized_start=80
  _globals['_MOVIEID']._serialized_end=101
  _globals['_DATES']._serialized_start=103
  _globals['_DATES']._serialized_end=132
  _globals['_SCHEDULEDATA']._serialized_start=134
  _globals['_SCHEDULEDATA']._serialized_end=178
  _globals['_EMPTY']._serialized_start=180
  _globals['_EMPTY']._serialized_end=187
  _globals['_SCHEDULE']._serialized_start=190
  _globals['_SCHEDULE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
